spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.107:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
      default-property-inclusion: non_null
server:
  context-path: /sell

wechat:
    mpAppId: wx3a4bb68bdb715901
    mpAppSecret: 15dfe48713519587af525a7c842efe51